### PR TITLE
Configure project to run in kubernetes env

### PR DESCRIPTION
**Pull request by pktherock**
- [x] Add Docker and .dockerignore  file
- [x] add script to create and deploy local build

### CODE REVIEW

**Comment by abhishekanandok** [comment]
✅ looks great

**Review by teamharsh — APPROVED** [review]
Approve

**Comment by Prity25-coder** [comment]
Approve

**Review by Prity25-coder — COMMENTED** [review]
Approve #1

**Comment by saifullahansari7** [comment]
Approved

**Pull request merged**
